-- Intentionally empty compatibility placeholder.
-- The column privilege hardening migration was applied to the linked RDS-NEARBY
-- project as version 20261010070600 and is tracked in
-- 20261010070600_phase17_column_privilege_hardening.sql.
-- Do not add SQL here. This file is retained because the repository connector
-- refused deletion; remove it during a normal reviewed Git cleanup.
